-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.api_metrics
(
    id serial NOT NULL,
    endpoint character varying(255) COLLATE pg_catalog."default",
    method character varying(10) COLLATE pg_catalog."default",
    response_time double precision,
    status_code integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT api_metrics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id serial NOT NULL,
    user_id integer,
    manuscript_id integer,
    action character varying(255) COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address character varying(50) COLLATE pg_catalog."default",
    browser text COLLATE pg_catalog."default",
    device text COLLATE pg_catalog."default",
    endpoint text COLLATE pg_catalog."default",
    old_value jsonb,
    new_value jsonb,
    status character varying(50) COLLATE pg_catalog."default",
    request_id uuid,
    session_id character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dashboard_statistics
(
    id serial NOT NULL,
    total_manuscripts integer,
    accepted integer,
    rejected integer,
    review integer,
    average_confidence double precision,
    average_processing_time double precision,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dashboard_statistics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.editorial_features
(
    id serial NOT NULL,
    manuscript_id integer NOT NULL,
    feature_name character varying(100) COLLATE pg_catalog."default",
    feature_value double precision,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT editorial_features_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.experiments
(
    id serial NOT NULL,
    experiment_name character varying(255) COLLATE pg_catalog."default",
    model_version character varying(100) COLLATE pg_catalog."default",
    metrics jsonb,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    dataset_name character varying(255) COLLATE pg_catalog."default",
    classifier character varying(100) COLLATE pg_catalog."default",
    calibration_method character varying(100) COLLATE pg_catalog."default",
    prompt_version character varying(50) COLLATE pg_catalog."default",
    random_seed integer,
    training_time double precision,
    experiment_status character varying(50) COLLATE pg_catalog."default",
    mlflow_run_id character varying(255) COLLATE pg_catalog."default",
    accuracy double precision,
    "precision" double precision,
    recall double precision,
    f1 double precision,
    auroc double precision,
    ece double precision,
    CONSTRAINT experiments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.explanations
(
    id serial NOT NULL,
    model_run_id integer NOT NULL,
    explanation_text text COLLATE pg_catalog."default",
    detected_issues jsonb,
    evidence_spans jsonb,
    CONSTRAINT explanations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.extracted_sections
(
    id serial NOT NULL,
    manuscript_id integer NOT NULL,
    section_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default",
    word_count integer,
    CONSTRAINT extracted_sections_pkey PRIMARY KEY (id),
    CONSTRAINT extracted_sections_manuscript_id_section_name_key UNIQUE (manuscript_id, section_name)
);

CREATE TABLE IF NOT EXISTS public.llm_evaluations
(
    id serial NOT NULL,
    manuscript_id integer NOT NULL,
    abstract_clarity double precision,
    structural_completeness double precision,
    methodological_strength double precision,
    experimental_strength double precision,
    argumentative_quality double precision,
    scope_alignment double precision,
    overall_quality double precision,
    research_paper_likelihood double precision,
    integrity_risk_score double precision,
    is_probably_research_paper boolean,
    detected_issues jsonb,
    evidence_spans jsonb,
    final_integrity_decision character varying(50) COLLATE pg_catalog."default",
    recommendation character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT llm_evaluations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.manuscripts
(
    id serial NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default",
    upload_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    num_pages integer,
    total_word_count integer,
    ground_truth boolean DEFAULT false,
    user_id integer,
    CONSTRAINT manuscripts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.model_runs
(
    id serial NOT NULL,
    manuscript_id integer NOT NULL,
    model_version character varying(100) COLLATE pg_catalog."default",
    experiment_id integer,
    threshold_profile_id integer,
    execution_time_ms integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    abstract_clarity double precision,
    structural_completeness double precision,
    methodological_strength double precision,
    experimental_strength double precision,
    argumentative_quality double precision,
    scope_alignment double precision,
    overall_quality double precision,
    prompt_version character varying(50) COLLATE pg_catalog."default",
    prompt_text text COLLATE pg_catalog."default",
    input_payload jsonb,
    raw_output text COLLATE pg_catalog."default",
    parsed_output jsonb,
    model_id integer,
    prompt_template_id integer,
    CONSTRAINT model_runs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.models
(
    id serial NOT NULL,
    model_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    version character varying(50) COLLATE pg_catalog."default",
    provider character varying(100) COLLATE pg_catalog."default",
    model_type character varying(100) COLLATE pg_catalog."default",
    context_length integer,
    parameters bigint,
    is_active boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    latency_ms integer,
    gpu_memory character varying(50) COLLATE pg_catalog."default",
    total_predictions integer DEFAULT 0,
    last_used timestamp without time zone,
    health_status character varying(30) COLLATE pg_catalog."default" DEFAULT 'Healthy'::character varying,
    CONSTRAINT models_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    user_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.predictions
(
    id serial NOT NULL,
    model_run_id integer NOT NULL,
    predicted_label boolean,
    desk_reject_probability double precision,
    confidence double precision,
    CONSTRAINT predictions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.processing_jobs
(
    id serial NOT NULL,
    manuscript_id integer,
    status character varying(50) COLLATE pg_catalog."default",
    progress integer DEFAULT 0,
    started_at timestamp without time zone,
    finished_at timestamp without time zone,
    error_message text COLLATE pg_catalog."default",
    queue_position integer,
    worker_name character varying(100) COLLATE pg_catalog."default",
    estimated_finish timestamp without time zone,
    CONSTRAINT processing_jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prompt_templates
(
    id serial NOT NULL,
    name character varying(150) COLLATE pg_catalog."default",
    version character varying(30) COLLATE pg_catalog."default",
    system_prompt text COLLATE pg_catalog."default",
    user_prompt text COLLATE pg_catalog."default",
    is_active boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT prompt_templates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reports
(
    id serial NOT NULL,
    manuscript_id integer NOT NULL,
    report_path text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    report_json jsonb,
    generated_by integer,
    download_count integer DEFAULT 0,
    last_download timestamp without time zone,
    export_format character varying(20) COLLATE pg_catalog."default" DEFAULT 'pdf'::character varying,
    CONSTRAINT reports_pkey PRIMARY KEY (id),
    CONSTRAINT unique_reports_manuscript_id UNIQUE (manuscript_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.rule_checks
(
    id serial NOT NULL,
    manuscript_id integer NOT NULL,
    rule_name character varying(100) COLLATE pg_catalog."default",
    severity character varying(20) COLLATE pg_catalog."default",
    passed boolean,
    description text COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rule_checks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.system_health
(
    id serial NOT NULL,
    service_name character varying(100) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    cpu_usage double precision,
    memory_usage double precision,
    disk_usage double precision,
    checked_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT system_health_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.system_settings
(
    id serial NOT NULL,
    auto_reject_threshold double precision,
    manual_review_threshold double precision,
    CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.threshold_history
(
    id serial NOT NULL,
    profile_id integer,
    changed_by integer,
    reject_threshold double precision,
    review_threshold double precision,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT threshold_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.threshold_profiles
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    reject_threshold double precision,
    review_threshold double precision,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    min_abstract_words integer DEFAULT 150,
    max_abstract_words integer DEFAULT 240,
    min_keywords integer DEFAULT 3,
    max_keywords integer DEFAULT 8,
    min_references integer DEFAULT 15,
    max_references integer DEFAULT 50,
    min_journal_self_citations integer DEFAULT 2,
    max_journal_self_citations integer DEFAULT 4,
    max_citations_from_any_journal integer DEFAULT 5,
    max_self_citations_by_authors integer DEFAULT 4,
    min_ratio_recent_citations double precision DEFAULT 0.3,
    min_manuscript_words integer DEFAULT 8000,
    max_manuscript_words integer DEFAULT 15000,
    required_sections text[] COLLATE pg_catalog."default" DEFAULT ARRAY['abstract'::text, 'introduction'::text, 'methodology'::text, 'conclusions'::text, 'references'::text],
    max_missing_sections integer DEFAULT 2,
    min_section_words integer DEFAULT 100,
    min_pages integer DEFAULT 4,
    max_pages integer DEFAULT 20,
    CONSTRAINT threshold_profiles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_activity
(
    id serial NOT NULL,
    user_id integer,
    activity character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_activity_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_preferences
(
    id serial NOT NULL,
    user_id integer,
    theme character varying(20) COLLATE pg_catalog."default" DEFAULT 'dark'::character varying,
    language character varying(20) COLLATE pg_catalog."default" DEFAULT 'en'::character varying,
    dashboard_layout character varying(100) COLLATE pg_catalog."default",
    items_per_page integer DEFAULT 10,
    CONSTRAINT user_preferences_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default",
    role_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    avatar_url text COLLATE pg_catalog."default",
    phone character varying(30) COLLATE pg_catalog."default",
    institution character varying(255) COLLATE pg_catalog."default",
    department character varying(255) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    last_login timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_audit_logs_user
    ON public.audit_logs(user_id);


ALTER TABLE IF EXISTS public.editorial_features
    ADD CONSTRAINT editorial_features_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.explanations
    ADD CONSTRAINT explanations_model_run_id_fkey FOREIGN KEY (model_run_id)
    REFERENCES public.model_runs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.extracted_sections
    ADD CONSTRAINT extracted_sections_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.llm_evaluations
    ADD CONSTRAINT llm_evaluations_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.manuscripts
    ADD CONSTRAINT manuscripts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.model_runs
    ADD CONSTRAINT fk_prompt_template FOREIGN KEY (prompt_template_id)
    REFERENCES public.prompt_templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.model_runs
    ADD CONSTRAINT model_runs_experiment_id_fkey FOREIGN KEY (experiment_id)
    REFERENCES public.experiments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.model_runs
    ADD CONSTRAINT model_runs_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.model_runs
    ADD CONSTRAINT model_runs_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.model_runs
    ADD CONSTRAINT model_runs_threshold_profile_id_fkey FOREIGN KEY (threshold_profile_id)
    REFERENCES public.threshold_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notifications_user
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.predictions
    ADD CONSTRAINT predictions_model_run_id_fkey FOREIGN KEY (model_run_id)
    REFERENCES public.model_runs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_predictions_model_run
    ON public.predictions(model_run_id);


ALTER TABLE IF EXISTS public.processing_jobs
    ADD CONSTRAINT processing_jobs_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_generated_by_fkey FOREIGN KEY (generated_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS unique_reports_manuscript_id
    ON public.reports(manuscript_id);


ALTER TABLE IF EXISTS public.rule_checks
    ADD CONSTRAINT rule_checks_manuscript_id_fkey FOREIGN KEY (manuscript_id)
    REFERENCES public.manuscripts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.threshold_history
    ADD CONSTRAINT threshold_history_changed_by_fkey FOREIGN KEY (changed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.threshold_history
    ADD CONSTRAINT threshold_history_profile_id_fkey FOREIGN KEY (profile_id)
    REFERENCES public.threshold_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_activity
    ADD CONSTRAINT user_activity_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

END;